services:
  unbscholar.postgres.lib.unb.ca:
    build:
      context: .
    container_name: unbscholar.postgres.lib.unb.ca
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - ./env/postgres.env
    networks:
      - unbscholar.postgres.lib.unb.ca
networks:
  unbscholar.postgres.lib.unb.ca:
    name: unbscholar.postgres.lib.unb.ca
